### ISSUE TITLE
[Stable] [OSX / Linux] Drag & Drop Not Working

### ISSUE THREAD

**Issue by iairpolo** [jaruba/PowderPlayer#110]
I'm using Linux Mint 17.3, Powder Player v0.98
Developer Tools when I try to drug and drop a torrent file:
Uncaught Error: Cannot find module 'parse-torrent'   module.js:327
Module._resolveFilename    module.js:327
Module._load       module.js:264
Module.require      module.js:356
require       module.js:375
window.require     undefined:4
(anonymous function)   load.js:211
load.multiple     load.js:209 
load.dropped     load.js:302
holder.ondrop     files.js:17

Thanks for your hard work!! You're awesome!!

**Comment by jaruba** [comment]
Here you go:
http://powder.media/PowderPlayer_v0.98_fixed.tar.gz

You can also test out the pre-release of Powder Player Nightly (added just a few hours ago):
https://www.reddit.com/r/PowderPlayer/comments/4ralk2/powder_player_v100_prerelease_available_for/

**Comment by iairpolo** [comment]
I downloaded the Nightly preview and this issue es gone :+1: :smile: 
However, I found some other problems, should I open another issue for those? (I will do it tomorrow anyway)

**Comment by jaruba** [comment]
Yes, please create a different issue, I'm expecting a lot of bugs in the Nightly, that's why it's only a pre-release, OSX and Linux have not been tested too much yet so I'd appreciate any feedback.

Depending on how many things still need to be fixed to get the Nightly to a stable enough state on all platforms, I might also release v0.99 with just the drag and drop fix for OSX and Linux.

**Comment by jaruba** [comment]
No longer relevant as the Nightly version is now the Stable version
