### ISSUE TITLE
[Nightly] Play/Pause Button Glitches

### ISSUE THREAD

**Issue by bitnom** [jaruba/PowderPlayer#116]
Very often while streaming a torrent, the play/pause button will become reversed and unresponsive. Sometimes when I click pause, it will switch the icon but not pause the video. I then have to toggle it several times before it actually pauses or unpauses the video. Currently on 0.98 stable

**Comment by jaruba** [comment]
Uhm, I'm not sure if that's an actual glitch from the User Interface.

Powder uses VLC under the hood, and sometimes VLC will replay the last X seconds instead of going in the buffering state, while in this replay state, it won't respond to any pause/play commands until it reached it's last known playback index again. But this behavior can be seen in both 0.98 and 1.00..

I'll investigate it either way to make sure that this is the case and there isn't some other bug somewhere causing it. Thank you for reporting this issue! :)

**Comment by jaruba** [comment]
I don't believe this issue is of any relevance anymore.
