### ISSUE TITLE
[Nightly] screen turn off while watching

### ISSUE THREAD

**Issue by roeycohen** [jaruba/PowderPlayer#123]
hi @jaruba,

a friend of mine told me that while watching a video (on his pc monitor) his screen was turned off (because of power saving options).

he's using windows 10 with the annual upgrade.

maybe this can help:
https://developer.chrome.com/apps/power

**Comment by jaruba** [comment]
Electron has an API for this too: [powerSaveBlocker](https://github.com/electron/electron/blob/master/docs/api/power-save-blocker.md)

Integration in Powder:
https://github.com/jaruba/PowderPlayer/search?utf8=%E2%9C%93&q=powerSaveBlocker
https://github.com/jaruba/PowderPlayer/search?utf8=%E2%9C%93&q=togglePowerSave&type=Code

It's very possible that I didn't integrate it correctly as it was added at the very beginning of the project and much has changed since then. I've also received the same issue for MacOS too: https://github.com/jaruba/PowderPlayer/issues/115

So I'm certain that something is going wrong with it.

I even worked on a hack (an alternative way of keeping the computer awake) for this sort of issue in the past:
[computer-sleep](https://github.com/jaruba/computer-sleep)

That uses a very small video with no audio and injects it in the page (in the background), as HTML5 Video forces the OS to stay awake during playback.

**Comment by roeycohen** [comment]
how come you never noticed it yourself? :)

**Comment by jaruba** [comment]
I disabled screen power saving on the laptop and desktop :P

**Comment by roeycohen** [comment]
haha :) good thing we found this before going out to stable release.

**Comment by middevonian** [comment]
I am also seeing this behaviour with Powder Player 1.0.0 on a fully up-to-date Windows 10 PC.

**Comment by Armenm** [comment]
Please fix this ASAP. It is really annoying to watch a movie and move mouse all the time in order not to see black screen.

**Comment by jaruba** [comment]
Done, I fixed and tested it, it will be available in the next build of the nightly.

**Comment by Armenm** [comment]
Thanks @jaruba
