### ISSUE TITLE
Support m2ts video codec in near future ? | Nightley

### ISSUE THREAD

**Issue by Draxler** [jaruba/PowderPlayer#129]
Would Powder Nightley support this video format > m2ts < in near future?
[i think > m2ts < belong to Blu-Ray video format-codec - it's meant only for HQ content]

**Comment by jaruba** [comment]
Powder uses libVLC v2.2.4 under the hood, if VLC v2.2.4 supports m2ts, then it's only a matter of adding `m2ts` to the supported file extensions array in Powder and it would just work.

But, as you say this is a Blu-Ray video format, there may be issues. Because Powder uses VLC and Blu-Ray / DVD have click-through menus, Powder just renders the video frames from VLC (by using WebChimera.js), so all click-through menus are just frames, you can't click them in Powder.. this is a tech limitation that can't be fixed.

**Comment by Draxler** [comment]
m2ts is like mkv in a way.  m2ts format is whole video file.
It's not like DVD or BluRay which have have a lot of files in its folder where player must play this main folder with video files in it for movie to actually play.. 
m2ts is standalone video format (VLC suport this format) 
1file = > GoodMovie.m2ts  (17.3 GB) click and play

**Comment by jaruba** [comment]
I found a `.m2ts` file to test with, added support for the extension to Powder and it works fine. It will be available in the next Nightly release.

**Comment by Draxler** [comment]
great ,,, tnx
