### ISSUE TITLE
Airplay

### ISSUE THREAD

**Issue by ageorgios** [jaruba/PowderPlayer#143]
Airplay does not discover latest AppleTV player

**Comment by jaruba** [comment]
This is not the first time it's mentioned that the newest AppleTV has issues with Powder.

I should change the AppleTV discovery module, the one I'm using seems to not have been updated in some time. I'm a little surprised that there are discovery issues for AppleTV as I would of expected the newer ones to just use the Bonjour Service as the others.

Testing will be hard though as I don't have the newest AppleTV at my disposal.

**Comment by jaruba** [comment]
I've determined that the Airplay issue comes from a decision by Apple that from tvOS 10.2 upwards device verification is mandatory.

Bad news is this broke the Airplay implementation in previous Apple TV products too, not just the latest.

Good news is this broke the Airplay implementation in previous Apple TV products too, not just the latest.

Yes, that was intentionally a duplicate because I'm happy I don't need to buy Apple TV 4K just to try to fix this thing, they forced this change on Apple TV 3 too.

**Comment by jaruba** [comment]
Support for Airplay 2 has been added.

Please try the latest release of Powder Player: https://powder.media/download

I'll close this issue in the meanwhile, if you still have issues you can reopen it.
