### ISSUE TITLE
Is it crossplatform?

### ISSUE THREAD

**Issue by kensully** [jaruba/PowderPlayer#30]
Hi,
I didn't find any documentation if it's crossplatform.
I am on Ubuntu 14.04.2 platform. I wonder if it runs on it.
Thanks.
Kenn

**Comment by jaruba** [comment]
For the moment it is only available for Windows, I plan on releasing a Mac version as soon as I get some time, which should not be very complicated to make as all the dependencies of Powder Player also have a stable Mac version too.

Ubuntu is a bit more complicated to make because I'm using an NPAPI to accomplish this but NPAPI is deprecated in NW.js on Linux since v0.9.2, considering this, it is still possible though, because even if NPAPI isn't supported we've also finished [WebChimera.js Player](https://github.com/jaruba/wcjs-player) which is native to the node.js environment.

The current version of [WebChimera Player](https://github.com/jaruba/WebChimeraPlayer) that is used has a Qt QML engine and thus all the Player's UI are made in QML, the newly created [WebChimera.js Player](https://github.com/jaruba/wcjs-player) is windowless, so all the missing UI components need to be redone for HTML / CSS / JS.

**Comment by jaruba** [comment]
@kensully
Would you be willing to test Powder Player on Ubuntu? The latest master has the new player (which still needs a lot of testing), but it should be cross platform. I've tested it on Mac and everything seemed to be working fine at first glance.

[**See Building Instructions**](https://github.com/jaruba/PowderPlayer/wiki#linux)

**Comment by jaruba** [comment]
I have just released ``Powder Player v0.90`` for:

- [Windows - 32bit](https://github.com/jaruba/PowderPlayer/releases/download/v0.90/PowderPlayer_v0.90.exe)

- [OSX - 64bit](https://github.com/jaruba/PowderPlayer/releases/download/v0.90/PowderPlayer_v0.90.dmg)

- [Ubuntu - 64bit](https://github.com/jaruba/PowderPlayer/releases/download/v0.90/PowderPlayer_v0.90.tar.gz)

Please test the Ubuntu version if/when you can. I am marking this issue as closed until further notice.
