### ISSUE TITLE
Left/Right Arrows for Seeking

### ISSUE THREAD

**Issue by kvirusp** [jaruba/PowderPlayer#4]
Seek should be default on  left/right arrows

**Comment by jaruba** [comment]
Left / Right arrows might be problematic for those with a wireless keyboards (as it could fall over or people could press buttons by mistake.

But I think that giving the chance to users to customize their own hotkeys is a great feature to add.

Current seek HotKeys are:

Shift + Arrow Left / Arrow Right - Very short jump (3 seconds)

Alt + Arrow Left / Arrow Right - Short jump (10 seconds)

Ctrl + Arrow Left / Arrow Right - Medium jump (1 minute)

As mentioned at [WebChimera Player HotKeys](http://wiki.webchimera.org/Player_Hotkeys) Wiki page.

**Comment by kvirusp** [comment]
Use a % var of the total file 1 % for example
Regarding your previous  comment...  too meany buttons to push for something that should be simple.
Focus on 99% of the users who use stationary keyboards as opposed to the 1% that run around the house with their keyboard :P

**Comment by jaruba** [comment]
+1 for the comedic nature of your comment :))

**Comment by jaruba** [comment]
I'm closing this as there are 6 hotkeys that already do this, will not do it just for the commodity of pressing 1 button instead of 2.

As of seeking by a percent value of the total time, the idea is invalid as avi streams do not have a total time until fully downloaded, also, Powder is made to work with any video source, there are also real time streams that do not have a total time at all. As situations without a total time exist and are actually very common in Powder, this cannot be done.

For commodity's sake though, I will attempt to make the mouse scroll over the Progress Bar to also seek in the video. But this is a different topic.

**Comment by jaruba** [comment]
Powder Player now also supports mouse scroll over the progress bar to seek through the video.

**Comment by jaruba** [comment]
``Left`` / ``Right`` can now be used to seek through the video.
