### ISSUE TITLE
Playback stuttering

### ISSUE THREAD

**Issue by kodaxx** [jaruba/PowderPlayer#65]
Every time I use a magnet link, the playback stutters. It doesn't matter how long I wait past buffering. I've tried different filetypes and everything. Windows 10. I love PowderPlayer and I think it has the best interface/functionality of all players. If the stuttering goes away and it gets ChromeCast support, I see this being HUGE

**Comment by jaruba** [comment]
is the stuttering happening once right when the video ends downloading? or does it happen periodically? (ie: stutters a bit, works ok, stutters again, etc)

**Comment by kodaxx** [comment]
It happens periodically throughout the whole file. I thought maybe it was
just skipping chunks of data that it could not get from the swarm in time
and I also thought it could have been a code issue. But pausing and waiting
for it to download and trying different qualities and file formats had no
effect

**Comment by jaruba** [comment]
does it also happen after the download has completed?

**Comment by kodaxx** [comment]
I believe so, I will double check tonight and make sure so I don't mislead
you.

**Comment by jaruba** [comment]
i think i know the bug your talking about, it only starts happening after you skipped through the video a bit. Sometimes it happens if you skip forward then backward. I partially fixed this for the next version by switching from a streaming link to the local file (once it finishes downloading).

@Ivshti mentioned he knows more about this, saying it's a VLC issue, I've actually checked and it happens with VLC too. Apparently after skipping for a bit VLC starts requesting the same chunk from a stream multiple times in a row and the stuttering is a side effect of this erratic behavior.

**Comment by kodaxx** [comment]
Okay, I rarely ever skip through videos and I don't think I did on any of
these occasions. I will test that tonight as well to make sure

**Comment by jaruba** [comment]
Other then that it only just stutters a bit when the download has finished, but then recovers fast, this happens because it gets flooded by the `torrent-stream` engine with a lot of downloaded pieces exactly when it ends, this usually happens when small files are being downloaded at very high speeds, and is  fully fixed in the next version.. :)

**Comment by jaruba** [comment]
Btw @kodaxx , if this is a big issue for you, you can build Powder Player by following this guide:
https://github.com/jaruba/PowderPlayer/wiki

I think it might fix the issues you are having.

**Comment by jaruba** [comment]
I think this is fixed now, if there are still issues with the new version, please reopen the ticket.
