### ISSUE TITLE
Option to catalog and keep in library .torrent like we do on Ember, Mediaelch but for .torrent

### ISSUE THREAD

**Issue by samukets** [jaruba/PowderPlayer#78]
will be great if powder catalog .torrent and show torrent helth. Think that, today you download .torrent X but you dont want to see that now, then you create a playlist, maybe serie x season 1, and after you can put a images based on local images or import for URL to remember in future what is that, image and description like, Serie x, image x, description: this series talk about love.

indeed will be great if we can add some .torrent season do all upside and close powder, powder works on second plan and when we open powder see, powder on second plan manage that playlist, making downloads, now is just watch.

Something like popcorn time but created from user to powder do not infringe laws.

![image](https://cloud.githubusercontent.com/assets/2901904/12915312/2cd19ff2-cf09-11e5-976b-a098a0055b96.png)

![image](https://cloud.githubusercontent.com/assets/2901904/12915335/47010c3c-cf09-11e5-8612-c463fc2d1d31.png)

![image](https://cloud.githubusercontent.com/assets/2901904/12915389/8eadc912-cf09-11e5-9ce6-b0dfeb8975a6.png)

**Comment by jaruba** [comment]
I think that your request is outside the scope of this project. Powder is a player, it's purpose is to ease the access to media, the torrent integration is there to give access to a new resource of media.

The subject of a local movie / tv show library is a different matter and has been handled well by other developer teams. The most known local library is Kodi: http://kodi.tv/download/

To make Powder keep the media files instead of removing them on close, you can right click the video and select "Torrent" > "Close + Keep Files". Then just make sure to have Powder's download folder as the scan folder for Movies / TV Shows in Kodi.

To make Kodi start Powder instead of it's internal player (which is actually a pretty bad player), all you need to do is replace the file at:

`C:\Program Files (x86)\Kodi\system\playercorefactory.xml`
_(if installed on the default path for windows)_

with the file from this archive:
https://gist.github.com/jaruba/445d9d39fb6f3db44d9d/archive/bf4ca84bf71ffb931c8aa8ef29603d6cfd1ddaeb.zip
_(make sure to change the path to powder from it if your not on windows or did not install in the default path)_
